[install]
# where `bun install --global` installs packages
globalDir = "/opt/bun/install/global"

# where globally-installed package bins are linked
globalBinDir = "/opt/bun/bin"

[install.cache]
# the directory to use for the cache
dir = "/opt/bun/install/cache"

# when true, don't load from the global cache.
# Bun may still write to node_modules/.cache
disable = false

# when true, always resolve the latest versions from the registry
disableManifest = false
