name: hs

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ hs ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: fj0r/io


jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !endsWith(github.event.head_commit.message, '~') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0r
          password: ${{ secrets.GHCR_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      #- name: Build hs
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: hs
      #    file: hs/up.Dockerfile
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ghcup
      #    labels: ${{ steps.meta.outputs.labels }}

      #- name: Build x
      #  uses: docker/build-push-action@v4
      #  with:
      #    context: js
      #    file: js/Dockerfile
      #    push: ${{ github.event_name != 'pull_request' }}
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:xup
      #    labels: ${{ steps.meta.outputs.labels }}
      #    build-args: BASE_IMAGE=fj0rd/io:ghcup

      - name: Build hs
        uses: docker/build-push-action@v4
        with:
          context: hs
          file: hs/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:hs
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=ghcr.io/fj0r/io:x
            STACK_INFO_URL=https://www.stackage.org/lts
            STACK_RESOLVER=
            GHC_OS=deb11
