name: base

on:
  push:
    branches: [ main, base ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: fj0rd/io


jobs:
  build:

    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#na') }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: fj0rd
          password: ${{ secrets.DOCKER }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build base
        uses: docker/build-push-action@v4
        with:
          context: base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:base
          labels: ${{ steps.meta.outputs.labels }}

      - name: trigger io:base
        run: |
          for a in gateway vpn sidecar clash lego maddy; do
            curl -L -X POST https://api.github.com/repos/fj0r/0x/actions/workflows/${a}.yml/dispatches \
              -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
              -d '{"ref":"main","inputs":{}}'
          done

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: box
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      - name: trigger io:latest
        run: |
          for a in php java11 java flink pg15 playwright; do
            curl -L -X POST https://api.github.com/repos/fj0r/0x/actions/workflows/${a}.yml/dispatches \
              -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" \
              -H "Authorization: Bearer ${{ secrets.ACTIONS_KEY }}" \
              -d '{"ref":"main","inputs":{}}'
          done

